import nodemailer from 'nodemailer';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method not allowed' });
  }

  const { name, email, message } = req.body;

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  // --- ENHANCED EMAIL TEMPLATE ---
  const mailOptions = {
    from: `"Portfolio Alert" <nithinkumarbadduluri@gmail.com>`,
    to: 'nithinkumarbadduluri@gmail.com',
    replyTo: email, // Allows you to just click "Reply" in your email app
    subject: ` New Connection: ${name}`,
    text: `New message from ${name} (${email}): ${message}`,
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; background-color: #55a3f2; border: 1px solid #8aa1cf; border-radius: 12px; overflow: hidden;">
        <div style="background-color: #2563eb; padding: 20px; text-align: center;">
          <h1 style="color: white; margin: 0; font-size: 24px; letter-spacing: 1px;">Hello!! NITHIN KUMAR</h1>
          <p style="color: #bfdbfe; margin: 5px 0 0 0; font-size: 14px;">Portfolio Inquiry Received</p>
        </div>

        <div style="padding: 30px; background-color: white;">
          <div style="margin-bottom: 25px;">
            <p style="color: #6b7280; font-size: 12px; text-transform: uppercase; font-weight: bold; margin-bottom: 5px;">Sender Details</p>
            <p style="margin: 0; font-size: 16px; color: #111827;"><strong>Name:</strong> ${name}</p>
            <p style="margin: 5px 0 0 0; font-size: 16px; color: #2563eb;"><strong>Email:</strong> ${email}</p>
          </div>

          <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; border-left: 4px solid #2563eb;">
            <p style="color: #6b7280; font-size: 12px; text-transform: uppercase; font-weight: bold; margin-bottom: 10px;">Message Contents</p>
            <p style="margin: 0; font-size: 15px; line-height: 1.6; color: #374151; font-style: italic;">"${message}"</p>
          </div>

          <div style="margin-top: 30px; text-align: center;">
            <a href="mailto:${email}" style="background-color: #2563eb; color: white; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: bold; font-size: 14px; display: inline-block;">Reply to ${name}</a>
          </div>
        </div>

        <div style="background-color: #f9fafb; padding: 15px; text-align: center; border-top: 1px solid #8aa1cf;">
          <p style="color: #343639; font-size: 11px; margin: 0;">This email was generated by your Portfolio Website .</p>
        </div>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    return res.status(200).json({ success: true });
  } catch (error) {
    return res.status(500).json({ error: error.message });
  }
}